import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ShopContextProvider from "./dashboard/ShopContext";
import { AuthProvider } from "./AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <ShopContextProvider>
        <body className={inter.className}>{children}</body>
      </ShopContextProvider>
      </AuthProvider>
    </html>
  );
}
